project:
  type: website
  output-dir: docs

website:
  title: "R Workshop"
  site-url: https://osu-codeclub.github.io/carpentries-aug-2026
  repo-url: https://github.com/osu-codeclub/carpentries-aug-2026
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - text: "0: Installation"
        href: 0_setup.qmd
      - text: "1: Intro"
        href: 1_intro.qmd
      - text: "2: Vectors and Data Types"
        href: 2_vectors.qmd
      - text: "3: Data Wrangling"
        href: 3_dplyr.qmd
      - text: "4: Data Visualization"
        href: 4_ggplot.qmd
    right:
      - text: "To learn more"
        menu:
        - text: Bonus material
          href: bonus.qmd
        - text: "------------------"
        - text: OSU Code Club {{< fa external-link >}}
          href: https://osu-codeclub.github.io
          target: _blank
        - text: Full Carpentries workshop page {{< fa external-link >}}
          href: https://cfaes-bioinfo.github.io/2026-08-17-osu-online
          target: _blank
        - text: Companion workshop on Version Control with Git {{< fa external-link >}}
          href: https://library.osu.edu/events/version-control-with-git-0
          target: _blank
        - text: Other OSU coding activities {{< fa external-link >}}
          href: https://osu-codeclub.github.io/pages/other.html
          target: _blank
        - text: "------------------"
        - text: OSU Research Commons {{< fa external-link >}}
          href: https://library.osu.edu/researchcommons
          target: _blank
        - text: The Carpentries {{< fa external-link >}}
          href: https://carpentries.org
          target: _blank
        - text: "------------------"
        - text: The full focal Carpentries lesson {{< fa external-link >}}
          href: https://swcarpentry.github.io/r-novice-gapminder
          target: _blank
        - text: R for Data Science ebook {{< fa external-link >}}
          href: https://r4ds.hadley.nz
          target: _blank
      - text: About
        href: about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/osu-codeclub/carpentries-aug-2026
            target: _blank
          - text: Report an Issue
            url:  https://github.com/osu-codeclub/carpentries-aug-2026/issues/new?template=Blank+issue
            target: _blank

format:
  html:
    theme: yeti
    syntax-highlighting: atom-one
    css:
      - styles.css
      - include/webex.css
    include-after-body: include/webex.js
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 800px

execute:
  freeze: auto

knitr:
  opts_chunk:
    class-output: regular-r-output
    class-message: regular-r-output
    class-warning: warning-r-output
    class-error: error-r-output
