{
  "hash": "9be0e2afc097e59f6490f85cbe30f10c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Data wrangling with _dplyr_\"\nauthor:\n  - name: Software Carpentry\n  - name: Jelmer Poelstra\n    orcid: 0000-0002-3514-7462\n    email: poelstra.1@osu.edu\n    affiliation: \n      - name: CFAES Bioinformatics Core, Ohio State University\n        url: https://go.osu.edu/bioinformatics-core\ndate: 2026-06-08\ndate-modified: last-modified\nengine: knitr\nformat:\n  live-html:\n    theme: yeti\n    syntax-highlighting: atom-one\n    css:\n      - styles.css\n      - include/webex.css\n    include-after-body: include/webex.js\n    toc: true\n    number-sections: true\n    number-depth: 3\n    grid:\n      body-width: 800px\nwebr:\n  cell-options:\n    autorun: true\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.cell context='setup'}\n```{webr}\n#| label: setup\n#| include: false\n#| context: setup\nlibrary(gapminder)\nlibrary(dplyr)\n```\n:::\n\n\n-------\n\n<br>\n\n## Introduction\n\n### What we'll cover\n\nMany of the most common data analysis tasks involve working with **tabular data**,\ni.e. data with rows and columns. In this session,\nyou'll learn to work with tabular data in R using the _dplyr_ package.\n\nFor example, you'll see how to subset, manipulate and summarize a dataset,\nthe kinds of tasks commonly referred to as \"data wrangling\".\nSuch data processing is often essential before you can move on to say,\ndata visualization (next session of this workshop) or statistical analyses.\n\n### Setting up\n\nUse a new script for this session, much like we did for the previous one:\n\n1. _Open a new R script_ (Click the **`+`** symbol in toolbar at the top, then click `R Script`)^[\n   Or Click `File` => `New file` => `R Script`.].\n   \n2. _Save the script_ straight away as `data-wrangling.R` --\n   you can save it anywhere you like, though it is probably best to save it in a\n   folder specifically for this workshop.\n   \n3. If you want the section headers as comments in your script,\n   like in the script I am showing you in the live session,\n   then copy-and-paste the following into your script:\n\n   <details><summary>Section headers for your script _(Click to expand)_</summary>\n\n   ::: {.cell}\n   \n   ```{.r .cell-code}\n   # TODO - UPDATE\n   \n   # 1 - Introduction ----------------------------------------------------\n   # 1.4 - Loading the tidyverse\n   \n   # 2 - The gapminder dataset  ------------------------------------------\n   \n   # Challenge 1\n   \n   # 3 - arrange() -------------------------------------------------------\n   \n   # Challenge 2\n   \n   # 4 - filter() --------------------------------------------------------\n   # 4.1 - Filter based on one condition\n   \n   # 4.2 - Filter based on multiple conditions\n   \n   # 5 - The pipe --------------------------------------------------------\n   \n   # Challenge 3\n   \n   # Challenge 4\n   \n   # 6 - mutate() --------------------------------------------------------\n   \n   # Challenge 5\n   \n   # 7 - summarize() -----------------------------------------------------\n   \n   # Challenge 6\n   ```\n   :::\n\n\n   </details>\n\n### The _dplyr_ package and the tidyverse\n\nOne of R's most powerful features is its ability to deal with **tabular data**:\ndata with rows and columns like you are familiar with from Excel spreadsheets\nand so on --- for example:\n\n<hr style=\"height:1pt; visibility:hidden;\" />\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n      country continent year lifeExp      pop gdpPercap\n1 Afghanistan      Asia 1952  28.801  8425333  779.4453\n2 Afghanistan      Asia 1957  30.332  9240934  820.8530\n3 Afghanistan      Asia 1962  31.997 10267083  853.1007\n4 Afghanistan      Asia 1967  34.020 11537966  836.1971\n5 Afghanistan      Asia 1972  36.088 13079460  739.9811\n6 Afghanistan      Asia 1977  38.438 14880372  786.1134\n```\n\n\n:::\n:::\n\n\nIn R, tabular data is stored in a data structure called \"**data frame**\".\nThe [_dplyr_](https://cran.r-project.org/package=dplyr) package provides very\nuseful functions for **manipulating data in data frames**.\nIn this session, we'll cover these commonly used _dplyr_ functions:\n\n- `arrange()` to change the order of rows (i.e., to sort a data frame)\n- `filter()` to keep only a subset of rows\n- `mutate()` to manipulate columns and create new columns\n- `summarize()` to compute data summaries across rows\n\n_dplyr_ has many more functions.\nSome of these are more advanced than those we'll cover today,\nwhile others are conceptually simpler\n(e.g. `rename()` to change column names and `select()` to select columns),\nand we encourage you to [explore](#bonus-material-for-self-study) these\n[on your own](https://dplyr.tidyverse.org/articles/dplyr.html). \n\n_dplyr_ belongs to a **family of R packages for data science called the**\n[\"tidyverse\"](https://www.tidyverse.org).**\nAnother tidyverse package we'll cover in today's workshop is _ggplot2_\nfor making plots.\n\n### Loading the tidyverse\n\nAll core tidyverse packages can be installed and loaded with a single command.\nSince you should already have _installed_ the tidyverse^[\nIf not: run `install.packages(\"tidyverse\")` now.\n], you only need to _load_ it, which you do as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n``` regular-r-output\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\nThe output tells you which packages have been loaded as part of the tidyverse.\n(For now, you don't have to pay attention to or worry about the\n[\"Conflicts\" section](#function-name-conflicts).)\n\n## The `gapminder` dataset\n\nIn this session and the next one on data visualization,\nwe will work with the `gapminder` dataset,\nwhich contains statistics such as population size for different countries across\nfive-year intervals.\n\nThis dataset is available in a package of the same name,\nwhich you already should have installed as well^[\nIf not: run `install.packages(\"gapminder\")` now.\n]. To load the package into your current R session:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# (Unlike with the tidyverse, no output is expected when you load gapminder)\nlibrary(gapminder)\n```\n:::\n\n\nTake a look at the `gapminder` data frame that is now available to you:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapminder\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1,704 × 6\n   country     continent  year lifeExp      pop gdpPercap\n   <fct>       <fct>     <int>   <dbl>    <int>     <dbl>\n 1 Afghanistan Asia       1952    28.8  8425333      779.\n 2 Afghanistan Asia       1957    30.3  9240934      821.\n 3 Afghanistan Asia       1962    32.0 10267083      853.\n 4 Afghanistan Asia       1967    34.0 11537966      836.\n 5 Afghanistan Asia       1972    36.1 13079460      740.\n 6 Afghanistan Asia       1977    38.4 14880372      786.\n 7 Afghanistan Asia       1982    39.9 12881816      978.\n 8 Afghanistan Asia       1987    40.8 13867957      852.\n 9 Afghanistan Asia       1992    41.7 16317921      649.\n10 Afghanistan Asia       1997    41.8 22227415      635.\n# ℹ 1,694 more rows\n```\n\n\n:::\n:::\n\n\nThe first 10 rows are printed, with the following columns:\n\n| column name | data type | meaning |\n|---|---|------|\n| `country` | `factor` (`<fct>`) | Country |\n| `continent` | `factor` (`<fct>`) | Continent that the country is in |\n| `year` | `integer` (`<int>`) | Focal year for the stats in the next columns |\n| `lifeExp` | `integer` (`<int>`) | Mean life expectancy in years |\n| `pop` | `integer` (`<int>`) | Population size |\n| `gdpPercap` | `double` (`<dbl>`) | Per-capita GDP |\n\n: {.striped}\n\n<hr style=\"height:1pt; visibility:hidden;\" />\n\nTwo columns are of type `factor`,\n[an alternative to](./2_vectors.qmd#factors) `character` commonly used for\ncategorical data.\n\nYou can also use the `View()` function to look at the data frame.\nThis will open a new tab in your editor pane with a spreadsheet-like look and feel:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nView(gapminder)\n# (Should display the dataset in an editor pane tab)\n```\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\nIn the `head()` output above,\nthe `gapminder` data frame is referred to as a *\"tibble\"*,\nwhich is just a slight variation on data frames from the tidyverse^[\nThe main difference is the nicer default printing behavior of tibbles:\ne.g. the data types of columns are shown,\nand only a limited number of rows are printed.].\n:::\n\n::: exercise\n#### {{< fa user-edit >}} **Challenge 1: Explore the `gapminder` dataset**\n\nTODO\n\n:::\n\n## `arrange()`\n\nThe `arrange()` function is like sorting functionality in Excel:\nit changes the order of rows based on the values in one or more columns.\nIt will always rearrange the order of rows as a whole,\nnever just of individual columns since that would scramble the data.\n\n`gapminder` is currently first sorted alphabetically by `country`,\nand next by `year`.\nBut you may, for example, want to sort by population size instead,\nwhich you can do with `arrange()` as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngm_arranged <- arrange(.data = gapminder, pop)\n```\n:::\n\n\nBefore we take a look at the result,\nlet's break down the syntax of the `arrange()` function:\n\n- The first argument is the data frame to be sorted,\n  which we specify with the `.data` argument.\n- The second argument is the column to sort by,\n  which we specify without an argument name.\n\n::: callout-note\n\nLike all _dplyr_ functions, `arrange()` outputs a new data frame,\nand **does not modify the input data frame.**\nIn this case, we chose to assign the output to a new object called `gm_arranged`.\n\n<details><summary>[{{< fa comments >}}]{style=\"color: darkgreen;\"} What would have happened if we had assigned the output to `gapminder`?</summary>\nIn that case, the original dataframe would have been overwritten with the sorted version.\n</details>\n\n<hr style=\"height:1pt; visibility:hidden;\" />\n:::\n\nNow let's look at the result of the sorting:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngm_arranged\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1,704 × 6\n   country               continent  year lifeExp   pop gdpPercap\n   <fct>                 <fct>     <int>   <dbl> <int>     <dbl>\n 1 Sao Tome and Principe Africa     1952    46.5 60011      880.\n 2 Sao Tome and Principe Africa     1957    48.9 61325      861.\n 3 Djibouti              Africa     1952    34.8 63149     2670.\n 4 Sao Tome and Principe Africa     1962    51.9 65345     1072.\n 5 Sao Tome and Principe Africa     1967    54.4 70787     1385.\n 6 Djibouti              Africa     1957    37.3 71851     2865.\n 7 Sao Tome and Principe Africa     1972    56.5 76595     1533.\n 8 Sao Tome and Principe Africa     1977    58.6 86796     1738.\n 9 Djibouti              Africa     1962    39.7 89898     3021.\n10 Sao Tome and Principe Africa     1982    60.4 98593     1890.\n# ℹ 1,694 more rows\n```\n\n\n:::\n:::\n\n\nSorting can help you find observations with the smallest or largest values\nfor a certain column: above, we see that the smallest population size in\nthe dataset is _Sao Tome and Principe_ in 1952.\n\nDefault sorting is from **small to large**, as seen above .\nTo sort in reverse order, use the `desc()` (descending) helper function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrange(.data = gapminder, desc(pop))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1,704 × 6\n   country continent  year lifeExp        pop gdpPercap\n   <fct>   <fct>     <int>   <dbl>      <int>     <dbl>\n 1 China   Asia       2007    73.0 1318683096     4959.\n 2 China   Asia       2002    72.0 1280400000     3119.\n 3 China   Asia       1997    70.4 1230075000     2289.\n 4 China   Asia       1992    68.7 1164970000     1656.\n 5 India   Asia       2007    64.7 1110396331     2452.\n 6 China   Asia       1987    67.3 1084035000     1379.\n 7 India   Asia       2002    62.9 1034172547     1747.\n 8 China   Asia       1982    65.5 1000281000      962.\n 9 India   Asia       1997    61.8  959000000     1459.\n10 China   Asia       1977    64.0  943455000      741.\n# ℹ 1,694 more rows\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip appearance='simple'}\nHere, we didn't assign the output to a new object, so it was just printed to screen.\nWe'll keep doing that for the rest of the examples in this session, \nso we can more easily see the results of the operations we are performing.\n:::\n\nFinally, you may want to sort by multiple columns,\nwhere ties in the first column are broken by a second column (and so on).\nDo this by simply listing the columns in the appropriate order:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sort first by continent, then by country:\narrange(.data = gapminder, continent, country)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1,704 × 6\n   country continent  year lifeExp      pop gdpPercap\n   <fct>   <fct>     <int>   <dbl>    <int>     <dbl>\n 1 Algeria Africa     1952    43.1  9279525     2449.\n 2 Algeria Africa     1957    45.7 10270856     3014.\n 3 Algeria Africa     1962    48.3 11000948     2551.\n 4 Algeria Africa     1967    51.4 12760499     3247.\n 5 Algeria Africa     1972    54.5 14760787     4183.\n 6 Algeria Africa     1977    58.0 17152804     4910.\n 7 Algeria Africa     1982    61.4 20033753     5745.\n 8 Algeria Africa     1987    65.8 23254956     5681.\n 9 Algeria Africa     1992    67.7 26298373     5023.\n10 Algeria Africa     1997    69.2 29072015     4797.\n# ℹ 1,694 more rows\n```\n\n\n:::\n:::\n\n\nPay attention to the syntax:\nadditional columns to sort by are additional arguments to the function,\nnot part of the same argument.\nOther _dplyr_ functions work equivalently in this regard.\n\n:::exercise\n#### {{< fa user-edit >}} **Challenge 2: `arrange()`**\n\nOne observation (row) in the `gapminder` dataset has the highest per-capita GDP.\nWhich line of code would you use to find out which row that is?\n\nTry it, and report which row (which country and year) you found.\n\n::: {.panel-tabset}\n\n#### {{< fa list-check >}} Quiz\n\n<div class='webex-radiogroup' id='radio_ETUKFOFXOC'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ETUKFOFXOC\" value=\"\"></input> <span>`arrange(.data = gapminder, desc(gdpPercap), year, country)`</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ETUKFOFXOC\" value=\"\"></input> <span>`arrange(.data = gapminder, country, year, gdpPercap)`</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ETUKFOFXOC\" value=\"answer\"></input> <span>`arrange(.data = gapminder, desc(gdpPercap))`</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ETUKFOFXOC\" value=\"\"></input> <span>`arrange(.data = gapminder, gdpPercap)`</span></label></div>\n\n#### {{< fa circle-info >}} Explanation\n\nWhile both the first and third options will give you the row with the highest per-capita GDP,\nthe first option will also sort the entire dataset by year and country,\nwhich is not necessary to answer the question.\n\nYou'll want to sort descendingly by `gdpPercap` to get the row with the highest value at the top.\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrange(.data = gapminder, desc(gdpPercap))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1,704 × 6\n   country   continent  year lifeExp     pop gdpPercap\n   <fct>     <fct>     <int>   <dbl>   <int>     <dbl>\n 1 Kuwait    Asia       1957    58.0  212846   113523.\n 2 Kuwait    Asia       1972    67.7  841934   109348.\n 3 Kuwait    Asia       1952    55.6  160000   108382.\n 4 Kuwait    Asia       1962    60.5  358266    95458.\n 5 Kuwait    Asia       1967    64.6  575003    80895.\n 6 Kuwait    Asia       1977    69.3 1140357    59265.\n 7 Norway    Europe     2007    80.2 4627926    49357.\n 8 Kuwait    Asia       2007    77.6 2505559    47307.\n 9 Singapore Asia       2007    80.0 4553009    47143.\n10 Norway    Europe     2002    79.0 4535591    44684.\n# ℹ 1,694 more rows\n```\n\n\n:::\n:::\n\n\nKuwait in 1957 had the highest per-capita GDP in the dataset, at $113,523.\n:::\n:::\n\n## `filter()`\n\nThe `filter()` function outputs only those rows that satisfy one or more conditions.\nIt is similar to Filter functionality in Excel.\n\n### Filter based on one condition\n\nThis first `filter()` example outputs only rows for which the\nlife expectancy exceeds 80 years\n(remember, each row represents a country in a given year):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(.data = gapminder, lifeExp > 80)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 21 × 6\n   country          continent  year lifeExp      pop gdpPercap\n   <fct>            <fct>     <int>   <dbl>    <int>     <dbl>\n 1 Australia        Oceania    2002    80.4 19546792    30688.\n 2 Australia        Oceania    2007    81.2 20434176    34435.\n 3 Canada           Americas   2007    80.7 33390141    36319.\n 4 France           Europe     2007    80.7 61083916    30470.\n 5 Hong Kong, China Asia       2002    81.5  6762476    30209.\n 6 Hong Kong, China Asia       2007    82.2  6980412    39725.\n 7 Iceland          Europe     2002    80.5   288030    31163.\n 8 Iceland          Europe     2007    81.8   301931    36181.\n 9 Israel           Asia       2007    80.7  6426679    25523.\n10 Italy            Europe     2002    80.2 57926999    27968.\n# ℹ 11 more rows\n```\n\n\n:::\n:::\n\n\n<details><summary>[{{< fa comments >}}]{style=\"color: darkgreen;\"} How many rows were output?</summary>\nAs is printed in the first line of the output, 21 rows were output.\n</details>\n\nAs the example above demonstrated,\n`filter()` **outputs rows that satisfy the condition(s)** you specify.\nThese conditions don't have to be based on numeric comparisons:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Only keep rows where the value in the 'continent' column is 'Europe':\nfilter(.data = gapminder, continent == \"Europe\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 360 × 6\n   country continent  year lifeExp     pop gdpPercap\n   <fct>   <fct>     <int>   <dbl>   <int>     <dbl>\n 1 Albania Europe     1952    55.2 1282697     1601.\n 2 Albania Europe     1957    59.3 1476505     1942.\n 3 Albania Europe     1962    64.8 1728137     2313.\n 4 Albania Europe     1967    66.2 1984060     2760.\n 5 Albania Europe     1972    67.7 2263554     3313.\n 6 Albania Europe     1977    68.9 2509048     3533.\n 7 Albania Europe     1982    70.4 2780097     3631.\n 8 Albania Europe     1987    72   3075321     3739.\n 9 Albania Europe     1992    71.6 3326498     2497.\n10 Albania Europe     1997    73.0 3428038     3193.\n# ℹ 350 more rows\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning appearance='simple'}\nRemember to use _two_ equals signs `==` to test for equality!\n:::\n\n### Filter based on multiple conditions\n\nIt's also possible to filter based on multiple conditions.\nFor example, you may want to see which countries in Asia had a life expectancy\ngreater than 80 years:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(.data = gapminder, continent == \"Asia\", lifeExp > 80)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 6 × 6\n  country          continent  year lifeExp       pop gdpPercap\n  <fct>            <fct>     <int>   <dbl>     <int>     <dbl>\n1 Hong Kong, China Asia       2002    81.5   6762476    30209.\n2 Hong Kong, China Asia       2007    82.2   6980412    39725.\n3 Israel           Asia       2007    80.7   6426679    25523.\n4 Japan            Asia       1997    80.7 125956499    28817.\n5 Japan            Asia       2002    82   127065841    28605.\n6 Japan            Asia       2007    82.6 127467972    31656.\n```\n\n\n:::\n:::\n\n\nLike above, by default, multiple conditions are combined using a Boolean ***AND***.\nIn other words, in a given row, _each_ condition must be met to output the row.\n\n::: {.callout-note collapse=\"true\"}\n#### What about a Boolean ***OR***? _(Click to expand)_\n\nIf you want to combine conditions using a Boolean ***OR***,\nwhere only one of the conditions needs to be met,\nuse a `|` (vertical bar) between the conditions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Keep rows with a high life expectancy and/or a high GDP:\nfilter(.data = gapminder, lifeExp > 80 | gdpPercap > 100000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 24 × 6\n   country          continent  year lifeExp      pop gdpPercap\n   <fct>            <fct>     <int>   <dbl>    <int>     <dbl>\n 1 Australia        Oceania    2002    80.4 19546792    30688.\n 2 Australia        Oceania    2007    81.2 20434176    34435.\n 3 Canada           Americas   2007    80.7 33390141    36319.\n 4 France           Europe     2007    80.7 61083916    30470.\n 5 Hong Kong, China Asia       2002    81.5  6762476    30209.\n 6 Hong Kong, China Asia       2007    82.2  6980412    39725.\n 7 Iceland          Europe     2002    80.5   288030    31163.\n 8 Iceland          Europe     2007    81.8   301931    36181.\n 9 Israel           Asia       2007    80.7  6426679    25523.\n10 Italy            Europe     2002    80.2 57926999    27968.\n# ℹ 14 more rows\n```\n\n\n:::\n:::\n\n:::\n\n## The pipe (`|>`)\n\nExamples so far applied a single _dplyr_ function to a data frame.\nBut in practice, it's common to use several consecutive _dplyr_ functions to\nwrangle a dataframe into the format you want.\n\nFor example, you may want to filter rows and then sort the result.\nYou could do that as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngm_filt <- filter(.data = gapminder, lifeExp < 50, year > 2000)\n\narrange(.data = gm_filt, desc(pop))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 42 × 6\n   country          continent  year lifeExp       pop gdpPercap\n   <fct>            <fct>     <int>   <dbl>     <int>     <dbl>\n 1 Nigeria          Africa     2007    46.9 135031164     2014.\n 2 Nigeria          Africa     2002    46.6 119901274     1615.\n 3 Congo, Dem. Rep. Africa     2007    46.5  64606759      278.\n 4 Congo, Dem. Rep. Africa     2002    45.0  55379852      241.\n 5 South Africa     Africa     2007    49.3  43997828     9270.\n 6 Tanzania         Africa     2002    49.7  34593779      899.\n 7 Afghanistan      Asia       2007    43.8  31889923      975.\n 8 Afghanistan      Asia       2002    42.1  25268405      727.\n 9 Uganda           Africa     2002    47.8  24739869      928.\n10 Mozambique       Africa     2007    42.1  19951656      824.\n# ℹ 32 more rows\n```\n\n\n:::\n:::\n\n\nAnd you could go on along these lines,\nsuccessively creating new objects that you then use for the next step.\n\nBut there is a more elegent way of dong this,\ndirectly sending (\"piping\") output from one function into the next function\nwith the **pipe operator** `|>`\n(a vertical bar followed by a greater-than sign).\nLet's start by seeing a reformulation of the code above with pipes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapminder |>\n  filter(lifeExp < 50, year > 2000) |>\n  arrange(desc(pop))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 42 × 6\n   country          continent  year lifeExp       pop gdpPercap\n   <fct>            <fct>     <int>   <dbl>     <int>     <dbl>\n 1 Nigeria          Africa     2007    46.9 135031164     2014.\n 2 Nigeria          Africa     2002    46.6 119901274     1615.\n 3 Congo, Dem. Rep. Africa     2007    46.5  64606759      278.\n 4 Congo, Dem. Rep. Africa     2002    45.0  55379852      241.\n 5 South Africa     Africa     2007    49.3  43997828     9270.\n 6 Tanzania         Africa     2002    49.7  34593779      899.\n 7 Afghanistan      Asia       2007    43.8  31889923      975.\n 8 Afghanistan      Asia       2002    42.1  25268405      727.\n 9 Uganda           Africa     2002    47.8  24739869      928.\n10 Mozambique       Africa     2007    42.1  19951656      824.\n# ℹ 32 more rows\n```\n\n\n:::\n:::\n\n\nWhat happened here? We took the `gapminder` data frame,\nsent (\"piped\") it into the `filter()` function,\nwhose output in turn was piped into the `arrange()` function.\nYou can think of the pipe as **\"then\"**:\ntake `gapminder`, _then_ filter, _then_ arrange.\n\nWhen using the pipe,\nyou no longer specify the input data frame with the `.data` argument,\nbecause the function now gets its input data via the pipe\n(specifically, the input goes to the function's first argument by default).\n\n::: {.callout-tip appearance='simple'}\nUsing pipes involves less typing and is especially more readable than using\nsuccessive assignments^[\nUsing pipes is also faster and uses less computer memory.\n].\nFor code readability, \nit is good practice to always start a new line after a pipe `|>`,\nand to keep the subsequent line(s) _indented_ as RStudio will automatically do.\n:::\n\n:::exercise\n#### {{< fa user-edit >}} **Challenge 3: Find the mistakes**\n\n::: {.panel-tabset}\n\n#### {{< fa list-check >}} Instructions\n\nThis pipeline is supposed to find the 3 countries with the lowest GDP per capita\nin 1997, sorted from lowest to highest.\nIt has two errors. Find and fix them:\n\n\n::: {.cell autorun='false' caption='' exercise='find_errors'}\n```{webr}\n#| autorun: false\n#| caption: \"\"\n#| exercise: find_errors\ngapminder\nfilter(year = 1997) |>\n  arrange(gdpPercap) |>\n  head(n = 3)\n```\n:::\n\n\n\n::: {.cell exercise='find_errors' check='true'}\n```{webr}\n#| exercise: find_errors\n#| check: true\nif (\n  identical(\n    .result,\n    gapminder |> filter(year == 1997) |> arrange(gdpPercap) |> head(n = 3)\n  )\n) {\n  list(correct = TRUE, message = \"Nice work, that is the correct answer!\")\n} else {\n  list(correct = FALSE, message = \"That's incorrect, sorry.\")\n}\n```\n:::\n\n\n#### {{< fa circle-check >}} Solution\n\n**The two errors are:**\n\n- Line 1: Missing pipe `|>` after gapminder\n- Line 2: Should use `==` (not `=`) to test for equality\n\n**Corrected code:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapminder |>\n  filter(year == 1997) |>\n  arrange(gdpPercap) |>\n  head(n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 3 × 6\n  country          continent  year lifeExp      pop gdpPercap\n  <fct>            <fct>     <int>   <dbl>    <int>     <dbl>\n1 Congo, Dem. Rep. Africa     1997    42.6 47798986      312.\n2 Myanmar          Asia       1997    60.3 43247867      415 \n3 Burundi          Africa     1997    45.3  6121610      463.\n```\n\n\n:::\n:::\n\n</details>\n\n:::\n:::\n\n:::exercise\n#### {{< fa user-edit >}} **Challenge 4: Find the extremes**\n\nUsing `filter()`, `arrange()`, and the pipe (`|>`),\nanswer the following questions about the gapminder dataset:\n\n::: {.panel-tabset}\n\n#### {{< fa list-check >}} Instructions\n\nA) Which African country had the highest life expectancy in 2002?\n\n#### {{< fa circle-check >}} Solution\n\nWe'll use the same trick with `head()` like in the exercise above\nto _only_ see the top 1 country, but this is not strictly necessary:\n   \n\n::: {.cell}\n\n```{.r .cell-code}\ngapminder |>\n  filter(continent == \"Africa\", year == 2002) |>\n  arrange(desc(lifeExp)) |>\n  head(n = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1 × 6\n  country continent  year lifeExp    pop gdpPercap\n  <fct>   <fct>     <int>   <dbl>  <int>     <dbl>\n1 Reunion Africa     2002    75.7 743981     6316.\n```\n\n\n:::\n:::\n\n\n:::\n::: {.panel-tabset}\n\n#### {{< fa list-check >}} Instructions\n\nB) What was the smallest population recorded in Asia across all years?\n\n#### {{< fa circle-check >}} Solution\n   \n\n::: {.cell}\n\n```{.r .cell-code}\ngapminder |>\n  filter(continent == \"Asia\") |>\n  arrange(pop) |>\n  head(n = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1 × 6\n  country continent  year lifeExp    pop gdpPercap\n  <fct>   <fct>     <int>   <dbl>  <int>     <dbl>\n1 Bahrain Asia       1952    50.9 120447     9867.\n```\n\n\n:::\n:::\n\n  \n:::\n:::\n\n## `mutate()`\n\nSo far, we've focused on functions that subset and reorganize data frames.\nBut you haven't seen how you can _change the data_ or _compute derived data_.\n\nThis can be done with the `mutate()` function.\nFor example, to create a new column with population sizes in millions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a new column 'pop_million' by dividing 'pop' by a million:\ngapminder |>\n  mutate(pop_million = pop / 10^6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1,704 × 7\n   country     continent  year lifeExp      pop gdpPercap pop_million\n   <fct>       <fct>     <int>   <dbl>    <int>     <dbl>       <dbl>\n 1 Afghanistan Asia       1952    28.8  8425333      779.        8.43\n 2 Afghanistan Asia       1957    30.3  9240934      821.        9.24\n 3 Afghanistan Asia       1962    32.0 10267083      853.       10.3 \n 4 Afghanistan Asia       1967    34.0 11537966      836.       11.5 \n 5 Afghanistan Asia       1972    36.1 13079460      740.       13.1 \n 6 Afghanistan Asia       1977    38.4 14880372      786.       14.9 \n 7 Afghanistan Asia       1982    39.9 12881816      978.       12.9 \n 8 Afghanistan Asia       1987    40.8 13867957      852.       13.9 \n 9 Afghanistan Asia       1992    41.7 16317921      649.       16.3 \n10 Afghanistan Asia       1997    41.8 22227415      635.       22.2 \n# ℹ 1,694 more rows\n```\n\n\n:::\n:::\n\n\nTo _modify_ an existing column rather than adding a new one,\nsimply \"assign back to the same name\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Change the unit of the 'pop' column:\ngapminder |>\n  mutate(pop = pop / 10^6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1,704 × 6\n   country     continent  year lifeExp   pop gdpPercap\n   <fct>       <fct>     <int>   <dbl> <dbl>     <dbl>\n 1 Afghanistan Asia       1952    28.8  8.43      779.\n 2 Afghanistan Asia       1957    30.3  9.24      821.\n 3 Afghanistan Asia       1962    32.0 10.3       853.\n 4 Afghanistan Asia       1967    34.0 11.5       836.\n 5 Afghanistan Asia       1972    36.1 13.1       740.\n 6 Afghanistan Asia       1977    38.4 14.9       786.\n 7 Afghanistan Asia       1982    39.9 12.9       978.\n 8 Afghanistan Asia       1987    40.8 13.9       852.\n 9 Afghanistan Asia       1992    41.7 16.3       649.\n10 Afghanistan Asia       1997    41.8 22.2       635.\n# ℹ 1,694 more rows\n```\n\n\n:::\n:::\n\n\n:::exercise\n#### {{< fa user-edit >}} **Challenge 5: Absolute GDP**\n\n::: {.panel-tabset}\n\n#### {{< fa list-check >}} Instructions\n\nUse `mutate()` to create a new column `gdp_billion` that has the\n**absolute** GDP (i.e., not relative to population size)\nin **units of billions**.\n\n\n::: {.cell autorun='false' caption='' exercise='abs_gdp'}\n```{webr}\n#| autorun: false\n#| caption: \"\"\n#| exercise: abs_gdp\ngapminder |>\n  mutate(______)\n```\n:::\n\n\n\n::: {.cell exercise='abs_gdp' check='true'}\n```{webr}\n#| exercise: abs_gdp\n#| check: true\nif (\n  identical(\n    .result,\n    gapminder |> mutate(gdp_billion = gdpPercap * pop / 10^9)\n  )\n) {\n  list(correct = TRUE, message = \"Nice work, that is the correct answer!\")\n} else {\n  list(correct = FALSE, message = \"That's incorrect, sorry.\")\n}\n```\n:::\n\n\n#### {{< fa lightbulb >}} Hints\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapminder |>\n  mutate(gdp_billion = gdpPercap * ______ / ______)\n```\n:::\n\n\n#### {{< fa circle-check >}} Solution\n\nYou need to do two things, which can be combined into a single line:\n\n1. Make the GDP absolute by multiplying by the population size: `gdpPercap * pop`\n2. Change the unit of the absolute GDP to billions by dividing by a billion:\n   ` / 10^9`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapminder |>\n  mutate(gdp_billion = gdpPercap * pop / 10^9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1,704 × 7\n   country     continent  year lifeExp      pop gdpPercap gdp_billion\n   <fct>       <fct>     <int>   <dbl>    <int>     <dbl>       <dbl>\n 1 Afghanistan Asia       1952    28.8  8425333      779.        6.57\n 2 Afghanistan Asia       1957    30.3  9240934      821.        7.59\n 3 Afghanistan Asia       1962    32.0 10267083      853.        8.76\n 4 Afghanistan Asia       1967    34.0 11537966      836.        9.65\n 5 Afghanistan Asia       1972    36.1 13079460      740.        9.68\n 6 Afghanistan Asia       1977    38.4 14880372      786.       11.7 \n 7 Afghanistan Asia       1982    39.9 12881816      978.       12.6 \n 8 Afghanistan Asia       1987    40.8 13867957      852.       11.8 \n 9 Afghanistan Asia       1992    41.7 16317921      649.       10.6 \n10 Afghanistan Asia       1997    41.8 22227415      635.       14.1 \n# ℹ 1,694 more rows\n```\n\n\n:::\n:::\n\n</details>\n\n:::\n:::\n\n## `summarize()`\n\nThe final function _dplyr_ function we'll cover is `summarize()`,\nwhich computes **summaries of your data across rows**.\nFor example, to calculate the mean GDP across the entire dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The syntax is similar to 'mutate': <new-column> = <operation>\ngapminder |>\n  summarize(mean_gdp = mean(gdpPercap))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1 × 1\n  mean_gdp\n     <dbl>\n1    7215.\n```\n\n\n:::\n:::\n\n\nThe output is still a dataframe, but unlike with all previous _dplyr_ functions,\nit is completely different from the input dataframe,\n\"collapsing\" the data down to as little as a single number, like above. \n\n`summarize()` becomes really powerful in combination with the helper function\n`group_by()` to compute **groupwise** stats.\nFor example, to get the mean GDP separately for each continent:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapminder |>\n  group_by(continent) |>\n  summarize(mean_gdp = mean(gdpPercap))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 5 × 2\n  continent mean_gdp\n  <fct>        <dbl>\n1 Africa       2194.\n2 Americas     7136.\n3 Asia         7902.\n4 Europe      14469.\n5 Oceania     18622.\n```\n\n\n:::\n:::\n\n\n`group_by()` implicitly splits a data frame into groups of rows:\nhere, one group for observations from each continent.\nAfter that, operations like in `summarize()` will happen separately for each group,\nwhich is how we ended up with per-continent means.\n\n:::exercise\n#### {{< fa user-edit >}} **Challenge 6: Mean life expectancy**\n\n::: {.panel-tabset}\n\n#### {{< fa list-check >}} Instructions\n\nA) Calculate the average life expectancy for each country and store the result in\n   a new dataframe.\n\n\n::: {.cell autorun='false' caption='' exercise='life_exp'}\n```{webr}\n#| autorun: false\n#| caption: \"\"\n#| exercise: life_exp\ngapminder |>\n  ______ |>\n  ______\n```\n:::\n\n\n\n::: {.cell exercise='life_exp' check='true'}\n```{webr}\n#| exercise: life_exp\n#| check: true\nif (\n  identical(\n    .result,\n    lifeExp_bycountry <- gapminder |> group_by(country) |> summarize(mean_lifeExp = mean(lifeExp))\n  )\n) {\n  list(correct = TRUE, message = \"Nice work, that is the correct answer!\")\n} else {\n  list(correct = FALSE, message = \"That's incorrect, sorry.\")\n}\n```\n:::\n\n\n#### {{< fa lightbulb >}} Hints\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlifeExp_bycountry <- gapminder |>\n  group_by(______) |>\n  summarize(mean_lifeExp = ______)\n```\n:::\n\n\n#### {{< fa circle-check >}} Solution\n\nFirst, create a dataframe with the mean life expectancy by country:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlifeExp_bycountry <- gapminder |>\n  group_by(country) |>\n  summarize(mean_lifeExp = mean(lifeExp))\n```\n:::\n\n\n:::\n::: {.panel-tabset}\n\n#### {{< fa list-check >}} Instructions\n\nB) Use the dataframe you just created to find out which country has the longest average\n   life expectancy and which has the shortest.\n\n#### {{< fa circle-check >}} Solution\n\nArrange the dataframe in two directions to see the countries with the\nlongest and shortest life expectancy.\nYou could optionally pipe into `head()` to only see the top `n`, here top 1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlifeExp_bycountry |>\n  arrange(mean_lifeExp) |>\n  head(n = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1 × 2\n  country      mean_lifeExp\n  <fct>               <dbl>\n1 Sierra Leone         36.8\n```\n\n\n:::\n\n```{.r .cell-code}\nlifeExp_bycountry |>\n  arrange(desc(mean_lifeExp)) |>\n  head(n = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` regular-r-output\n# A tibble: 1 × 2\n  country mean_lifeExp\n  <fct>          <dbl>\n1 Iceland         76.5\n```\n\n\n:::\n:::\n\n\nSo, **Sierra Leone** has the shortest average life expectancy (36.8 years),\nand **Iceland** has the longest average life expectancy (76.5 years).\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}